### PR TITLE
add .elpaignore

### PR DESCRIPTION
**Pull request by jtbx**
See: https://lists.gnu.org/archive/html/emacs-devel/2024-08/msg00424.html

### CODE REVIEW

**Review by CyberShadow — COMMENTED** [review]
Would it be possible to add a comment that explains what this file is or links to a page which does so?

**Comment by jtbx** [comment]
Line 446 of the ELPA [README](https://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/README) specifies that .elpaignore is passed to `tar -X`. The info node [(tar) Excluding Some Files](https://www.gnu.org/software/tar/manual/html_node/exclude.html) describes `-X` but there's nothing in there about comments allowed in the file. I could link to those in the commit message or start a line beginning with a hashtag in .elpaignore with those links which would still be parsed as a pattern.

**Comment by CyberShadow** [comment]
Unfortunate. I think the explanation here suffices. Thanks!

**Review by CyberShadow — APPROVED** [review]

**Comment by jtbx** [comment]
Thanks, rebasing onto master.

**Pull request merged**
