### PR TITLE
Major revision (complete overhaul of nearly everything)

### PR DESCRIPTION
**Pull request by CyberShadow**
Fixes a lot of bugs and I'm sure introduces many others. WIP.

Uploading this now as I'm taking a break from this project to work on https://github.com/CyberShadow/TrenD.

### CODE REVIEW

**Comment by nordlow** [comment]
Great work.

**Comment by nordlow** [comment]
Is this ready to go?

**Comment by CyberShadow** [comment]
No. There's still some things on my personal TODO that I want to fix. After that, I'd like to use it for a few days to try to spot regressions before pushing it to master. Help with testing what's here so far would be helpful.

**Comment by nordlow** [comment]
Is it possible to fontify const-qualified function parameters with parenthesises such as

```D
void f(const(Type) param);
```

?

**Comment by CyberShadow** [comment]
Anything is possible, file some issues and we can see if it's feasible.

**Comment by CyberShadow** [comment]
Hierarchical imenu:

screenshot

**Comment by CyberShadow** [comment]
That's everything from my list.

**Comment by atilaneves** [comment]
I'm just going to trust you on this one. Good work!

**Comment by nordlow** [comment]
The function 'rx-form` was just removed from Emacs master.

**Comment by nordlow** [comment]
Found the cornercase 

```D
struct S
{
    @safe:
    T x;
}
```

in which `T x` doesn't fontify, regardless of indentation of `@safe`.

**Comment by CyberShadow** [comment]
I actually found a *lot* of bugs / regressions. I'll add this to the pile :)

I hope I can get back to this as soon as I finish my current project, which is taking a bit longer than expected.

**Comment by nordlow** [comment]
Found one more cornercase:

Parameters qualified with `return` doesn't fontify type and name as in

```
void f(scope return int x)
{
}
```

.

**Comment by nordlow** [comment]
Thanks for the fixes.

This case doesn't fontify `C`:

```D
@safe:
class C { }
```

.

**Comment by nordlow** [comment]
This fontifies correctly now:

```D
@safe:
class C { }
```

Thanks!

**Comment by nordlow** [comment]
AFAICT, the first parameter to `__traits` should be fontified in `font-lock-builtin-face`.

**Comment by CyberShadow** [comment]
> AFAICT, the first parameter to `__traits` should be fontified in `font-lock-builtin-face`.

cc-mode only deals with types and refs in the mechanism we're using for fontification there. Not sure what the consequences would be of choosing to not use it and fontify the buffer directly.

**Comment by CyberShadow** [comment]
> Here's my attempt that does that:

Thanks. I'm trying to move away from regular expressions for anything bigger than single tokens, as they won't work with syntactic whitespace (i.e. comments).

**Comment by nordlow** [comment]
Qualifier `package` on `class`-definitions doesn't seem to fontify correctly, such as in

```D
package class C {}
```

**Comment by CyberShadow** [comment]
Sorry, I can't reproduce the problem:

https://github.com/CyberShadow/Emacs-D-Mode/commit/e69366fee35b03fc96941598bc4037f23e2c1171

Works fine for me.

**Comment by nordlow** [comment]
> Sorry, I can't reproduce the problem:
> 
> [CyberShadow@e69366f](https://github.com/CyberShadow/Emacs-D-Mode/commit/e69366fee35b03fc96941598bc4037f23e2c1171)
> 
> Works fine for me.

Strange. What Emacs version are you using? I'm currently sitting on Emacs master.

**Comment by CyberShadow** [comment]
26.3.

**Comment by CyberShadow** [comment]
I added the test case to this branch for CI, and it passed for all supported Emacs versions:

https://travis-ci.org/Emacs-D-Mode-Maintainers/Emacs-D-Mode/builds/637279679

**Comment by nordlow** [comment]
I put any more time into this for a while. Thanks.

**Comment by nordlow** [comment]
Does this fontify correctly for you?

```D
alias Expr = string[];

void toString(scope void delegate(scope const(char)[]) @safe sink,
              scope const Expr expr);
```

I get

```
Error during redisplay: (jit-lock-function 25) signaled (scan-error "Unbalanced parentheses" 38 101)
```

during fontification.

The `Expr` part of the second argument doesn't fonity at all.

**Comment by CyberShadow** [comment]
> The `Expr` part of the second argument doesn't fonity at all.

Same here (because of `@safe`), but I don't get the error.

**Comment by nordlow** [comment]
> > The `Expr` part of the second argument doesn't fonity at all.
> 
> Same here (because of `@safe`), but I don't get the error.

Ok, thanks. I'll see I can figure out the source of the error.

**Comment by CyberShadow** [comment]
Correction, I do see the error if I look in \*Messages\*.

**Comment by nordlow** [comment]
> Correction, I do see the error if I look in *Messages*.

Thanks.

**Comment by CyberShadow** [comment]
Alan Mackenzie, the maintainer of CC Mode, contacted Russell and me today regarding one use of Emacs Lisp advice in the current (master) version of d-mode:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=18158#26

As the changes in this PR introduce additional advice patches such as the one fixed by Alan's patch, I  replied inquiring about the possible future for d-mode going forward. My reply is below Alan's message at the link above.

**Comment by Geod24** [comment]
Any chance some of this could make it to the repository ? I'm particularly interested in https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode/pull/93/commits/1ec588075f5c2b5181257591ebc7ce33fa875e8e as it fixes #90 which makes working on `expression.d` quite painful...

**Comment by CyberShadow** [comment]
I think at this point it would have to be a fork or some kind of branch, because 1) it's much more difficult to maintain, and 2) it introduces its own regressions (which are perhaps less severe than the ones in master). Unfortunately we didn't get anywhere in the discussion with the cc-mode maintainer either.

**Comment by Geod24** [comment]
I've been using it daily for a month now, and bar for the little bug when writing function prototypes, it really works well.

**Comment by CyberShadow** [comment]
> I'd be in favor of just merging it, as mentioned earlier.

OK.

> And perhaps now is the time to ping the maintainer again ?

It's possible that we might get to a better place through collaboration, but that requires some expended time and effort from both sides. It does seem to me that time would be instead better spent on solutions based on language servers, so that all editors benefit from them, and we don't have to implement the same functionality once per editor.

**Pull request merged**
