### PR TITLE
add d-exceptions compilation error regexp

### PR DESCRIPTION
**Pull request by snosov1**
Hey!

This PR does 3 things:

- Adds a compilation error regexp that recognizes messages generated by the D runtime for unhandled exceptions (e.g. assert failures, like `core.exception.AssertError@/tmp/app.d(10): unittest failure`)
- Adds both `ldc` and the new `d-exceptions` rules to `compilation-error-regexp-alist` instead of suggesting to do so in the comment (does anyone read these comments?)
- Fixes the comments to be more positive (the stated uncertainties were verified)

### CODE REVIEW

**Comment by dmakarov** [comment]
I wrote these comments.  I guess I didn't want to enforce on users the modifications to a customizable variable ```compilation-error-regexp-alist```, but if someone wanted to use compilation mode with D, they could add the new symbol to the variable.

**Comment by snosov1** [comment]
I see your point. But in my opinion it should be the other way around. The vast majority of users will want it to be there by default and in rare cases this might not be desirable. So the users who don't want it should remove it.

**Comment by russel** [comment]
Can we come to a consensus on whether this should get committed to the mainline? We seems to have 1 for, 1 against, and 1 sitting on the fence (me :-).

**Comment by dmakarov** [comment]
Hi Russel,

In my opinion it's ok to commit.

**Comment by snosov1** [comment]
:+1:

**Pull request merged**
