### PR TITLE
Add LDC compiler message pattern to be recognized in compilation mode.

### PR DESCRIPTION
**Pull request by dmakarov**
This allows the LDC compiler message parsing in ```*compilation*``` mode.

### CODE REVIEW

**Comment by russel** [comment]
Thanks for sending this in.

**Comment by CyberShadow** [comment]
Seriously, please stop putting optimized regexp string literals in source files. This is what `rx` and `regexp-opt` is for. This is completely unmaintainable. At least add some tests...

**Comment by nordlow** [comment]
I agree.

**Comment by CyberShadow** [comment]
https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode/pull/69

**Pull request merged**
